version: '3.7'

services:
  chat-react:
    container_name: chat-react-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 80:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  couchdb:
    container_name: couchdb-dev
    image: library/couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    ports:
      - 5984:5984
    volumes:
      - couchdb_data:/couchdb
      - ./couchdb:/opt/couchdb/etc/local.d

volumes:
  couchdb_data:
    driver: local
